
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.17.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace THUMDER.CLI {
    using System;
    using Terminal.Gui;
    
    
    public partial class CLI : Terminal.Gui.Window {
        
        private Terminal.Gui.ColorScheme greenOnBlack;
        
        private Terminal.Gui.ColorScheme redOnBlack;
        
        private Terminal.Gui.ColorScheme blueOnBlack;
        
        private Terminal.Gui.ColorScheme Custom;
        
        private Terminal.Gui.ColorScheme greenOnBlack2;
        
        private Terminal.Gui.ColorScheme MenuScheme;
        
        private Terminal.Gui.MenuBar _MainMenu;
        
        private Terminal.Gui.MenuBarItem _FileF9;
        
        private Terminal.Gui.MenuItem _LoadFile;
        
        private Terminal.Gui.MenuItem _Quit;
        
        private Terminal.Gui.MenuBarItem _Run;
        
        private Terminal.Gui.MenuItem _Run2;
        
        private Terminal.Gui.MenuItem Breakpoint;
        
        private Terminal.Gui.MenuItem Stepover;
        
        private Terminal.Gui.MenuBarItem _View;
        
        private Terminal.Gui.MenuItem _Options;
        
        private Terminal.Gui.MenuItem _Results;
        
        private Terminal.Gui.MenuBarItem _Help;
        
        private Terminal.Gui.MenuItem _About;
        
        private Terminal.Gui.FrameView _FileFrame;
        
        private Terminal.Gui.ListView _FileView;
        
        private Terminal.Gui.FrameView _PipelineFrame;
        
        private Terminal.Gui.TreeView _PipelineTree;
        
        private Terminal.Gui.FrameView _MemoryFrame;
        
        private Terminal.Gui.ListView _MemoryAddressList;
        
        private Terminal.Gui.ListView _MemoryContent;
        
        private Terminal.Gui.FrameView _RegistersFrame;
        
        private Terminal.Gui.ListView _RegisterList;
        
        private Terminal.Gui.ListView _RegisterContent;
        
        private void InitializeComponent() {
            this._RegisterContent = new Terminal.Gui.ListView();
            this._RegisterList = new Terminal.Gui.ListView();
            this._RegistersFrame = new Terminal.Gui.FrameView();
            this._MemoryContent = new Terminal.Gui.ListView();
            this._MemoryAddressList = new Terminal.Gui.ListView();
            this._MemoryFrame = new Terminal.Gui.FrameView();
            this._PipelineTree = new Terminal.Gui.TreeView();
            this._PipelineFrame = new Terminal.Gui.FrameView();
            this._FileView = new Terminal.Gui.ListView();
            this._FileFrame = new Terminal.Gui.FrameView();
            this._MainMenu = new Terminal.Gui.MenuBar();
            this.greenOnBlack = new Terminal.Gui.ColorScheme();
            this.greenOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Green, Terminal.Gui.Color.Black);
            this.greenOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightGreen, Terminal.Gui.Color.Black);
            this.greenOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Green, Terminal.Gui.Color.Magenta);
            this.greenOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightGreen, Terminal.Gui.Color.Magenta);
            this.greenOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Gray, Terminal.Gui.Color.Black);
            this.redOnBlack = new Terminal.Gui.ColorScheme();
            this.redOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Red, Terminal.Gui.Color.Black);
            this.redOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightRed, Terminal.Gui.Color.Black);
            this.redOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Red, Terminal.Gui.Color.Brown);
            this.redOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightRed, Terminal.Gui.Color.Brown);
            this.redOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Gray, Terminal.Gui.Color.Black);
            this.blueOnBlack = new Terminal.Gui.ColorScheme();
            this.blueOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightBlue, Terminal.Gui.Color.Black);
            this.blueOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Cyan, Terminal.Gui.Color.Black);
            this.blueOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightBlue, Terminal.Gui.Color.BrightYellow);
            this.blueOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Cyan, Terminal.Gui.Color.BrightYellow);
            this.blueOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Gray, Terminal.Gui.Color.Black);
            this.Custom = new Terminal.Gui.ColorScheme();
            this.Custom.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Black);
            this.Custom.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.Brown);
            this.Custom.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Black);
            this.Custom.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.Brown);
            this.Custom.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Gray, Terminal.Gui.Color.Black);
            this.greenOnBlack2 = new Terminal.Gui.ColorScheme();
            this.greenOnBlack2.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Black);
            this.greenOnBlack2.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightGreen, Terminal.Gui.Color.Black);
            this.greenOnBlack2.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Green, Terminal.Gui.Color.Magenta);
            this.greenOnBlack2.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightGreen, Terminal.Gui.Color.Magenta);
            this.greenOnBlack2.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Gray, Terminal.Gui.Color.Black);
            this.MenuScheme = new Terminal.Gui.ColorScheme();
            this.MenuScheme.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.Gray);
            this.MenuScheme.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Brown, Terminal.Gui.Color.Gray);
            this.MenuScheme.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.DarkGray);
            this.MenuScheme.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Brown, Terminal.Gui.Color.DarkGray);
            this.MenuScheme.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Black);
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.ColorScheme = this.greenOnBlack;
            this.Modal = false;
            this.Text = "";
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.Effect3D = false;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "THUMDER Core";
            this._MainMenu.Width = Dim.Fill(0);
            this._MainMenu.Height = 1;
            this._MainMenu.X = Pos.Center();
            this._MainMenu.Y = 0;
            this._MainMenu.ColorScheme = this.MenuScheme;
            this._MainMenu.Data = "_MainMenu";
            this._MainMenu.Text = "";
            this._MainMenu.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this._FileF9 = new Terminal.Gui.MenuBarItem();
            this._FileF9.Title = "_File (F9)";
            this._LoadFile = new Terminal.Gui.MenuItem();
            this._LoadFile.Title = "_Load File";
            this._LoadFile.Data = "_LoadFile";
            this._LoadFile.Shortcut = ((Terminal.Gui.Key)(1073741900u));
            this._Quit = new Terminal.Gui.MenuItem();
            this._Quit.Title = "_Quit";
            this._Quit.Data = "_Quit";
            this._Quit.Shortcut = ((Terminal.Gui.Key)(1073741905u));
            this._FileF9.Children = new Terminal.Gui.MenuItem[] {
                    this._LoadFile,
                    this._Quit};
            this._Run = new Terminal.Gui.MenuBarItem();
            this._Run.Title = "_Run";
            this._Run2 = new Terminal.Gui.MenuItem();
            this._Run2.Title = "_Run";
            this._Run2.Data = "_Run2";
            this._Run2.Shortcut = ((Terminal.Gui.Key)(1048591u));
            this.Breakpoint = new Terminal.Gui.MenuItem();
            this.Breakpoint.Title = "_Breakpoint";
            this.Breakpoint.Data = "Breakpoint";
            this.Breakpoint.Shortcut = ((Terminal.Gui.Key)(1048592u));
            this.Stepover = new Terminal.Gui.MenuItem();
            this.Stepover.Title = "_Step over";
            this.Stepover.Data = "Stepover";
            this.Stepover.Shortcut = ((Terminal.Gui.Key)(1048594u));
            this._Run.Children = new Terminal.Gui.MenuItem[] {
                    this._Run2,
                    this.Breakpoint,
                    this.Stepover};
            this._View = new Terminal.Gui.MenuBarItem();
            this._View.Title = "_View";
            this._Options = new Terminal.Gui.MenuItem();
            this._Options.Title = "_Options";
            this._Options.Data = "_Options";
            this._Options.Shortcut = ((Terminal.Gui.Key)(1073741903u));
            this._Results = new Terminal.Gui.MenuItem();
            this._Results.Title = "_Results";
            this._Results.Data = "_Results";
            this._Results.Shortcut = ((Terminal.Gui.Key)(1073741906u));
            this._View.Children = new Terminal.Gui.MenuItem[] {
                    this._Options,
                    this._Results};
            this._Help = new Terminal.Gui.MenuBarItem();
            this._Help.Title = "_Help";
            this._About = new Terminal.Gui.MenuItem();
            this._About.Title = "_About";
            this._About.Data = "_About";
            this._About.Shortcut = ((Terminal.Gui.Key)(1048587u));
            this._Help.Children = new Terminal.Gui.MenuItem[] {
                    this._About};
            this._MainMenu.Menus = new Terminal.Gui.MenuBarItem[] {
                    this._FileF9,
                    this._Run,
                    this._View,
                    this._Help};
            this.Add(this._MainMenu);
            this._FileFrame.Width = Dim.Percent(50f);
            this._FileFrame.Height = Dim.Fill(0);
            this._FileFrame.X = 0;
            this._FileFrame.Y = Pos.Percent(0f) + 1;
            this._FileFrame.ColorScheme = this.greenOnBlack;
            this._FileFrame.Data = "_FileFrame";
            this._FileFrame.Text = "";
            this._FileFrame.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this._FileFrame.Border.Effect3D = false;
            this._FileFrame.Border.DrawMarginFrame = true;
            this._FileFrame.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this._FileFrame.Title = "File";
            this.Add(this._FileFrame);
            this._FileView.Width = Dim.Fill(0);
            this._FileView.Height = Dim.Fill(0);
            this._FileView.X = Pos.Center();
            this._FileView.Y = Pos.Center();
            this._FileView.ColorScheme = this.Custom;
            this._FileView.Data = "_FileView";
            this._FileView.Text = "";
            this._FileView.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this._FileView.Source = new Terminal.Gui.ListWrapper(new string[] {
                        "Line1",
                        "Line2",
                        "Line3",
                        ""});
            this._FileFrame.Add(this._FileView);
            this._PipelineFrame.Width = Dim.Fill(0);
            this._PipelineFrame.Height = Dim.Percent(50f);
            this._PipelineFrame.X = Pos.Right(_FileFrame);
            this._PipelineFrame.Y = 1;
            this._PipelineFrame.ColorScheme = this.greenOnBlack;
            this._PipelineFrame.Data = "_PipelineFrame";
            this._PipelineFrame.Text = "";
            this._PipelineFrame.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this._PipelineFrame.Border.Effect3D = false;
            this._PipelineFrame.Border.DrawMarginFrame = true;
            this._PipelineFrame.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this._PipelineFrame.Title = "Pipeline";
            this.Add(this._PipelineFrame);
            this._PipelineTree.Width = Dim.Fill(0);
            this._PipelineTree.Height = Dim.Fill(0);
            this._PipelineTree.X = Pos.Center();
            this._PipelineTree.Y = Pos.Center();
            this._PipelineTree.ColorScheme = this.greenOnBlack2;
            this._PipelineTree.Data = "_PipelineTree";
            this._PipelineTree.Text = "";
            this._PipelineTree.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this._PipelineTree.Style.CollapseableSymbol = '-';
            this._PipelineTree.Style.ColorExpandSymbol = false;
            this._PipelineTree.Style.ExpandableSymbol = '+';
            this._PipelineTree.Style.InvertExpandSymbolColors = false;
            this._PipelineTree.Style.LeaveLastRow = false;
            this._PipelineTree.Style.ShowBranchLines = true;
            this._PipelineFrame.Add(this._PipelineTree);
            this._MemoryFrame.Width = Dim.Percent(25f);
            this._MemoryFrame.Height = Dim.Fill(0);
            this._MemoryFrame.X = Pos.Right(_FileFrame);
            this._MemoryFrame.Y = Pos.Bottom(_PipelineFrame);
            this._MemoryFrame.ColorScheme = this.greenOnBlack;
            this._MemoryFrame.Data = "_MemoryFrame";
            this._MemoryFrame.Text = "";
            this._MemoryFrame.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this._MemoryFrame.Border.Effect3D = false;
            this._MemoryFrame.Border.DrawMarginFrame = true;
            this._MemoryFrame.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this._MemoryFrame.Title = "Memory";
            this.Add(this._MemoryFrame);
            this._MemoryAddressList.Width = Dim.Percent(50f);
            this._MemoryAddressList.Height = Dim.Fill(0);
            this._MemoryAddressList.X = 0;
            this._MemoryAddressList.Y = 0;
            this._MemoryAddressList.ColorScheme = this.Custom;
            this._MemoryAddressList.Data = "_MemoryAddressList";
            this._MemoryAddressList.Text = "";
            this._MemoryAddressList.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this._MemoryAddressList.Source = new Terminal.Gui.ListWrapper(new string[] {
                        "Address1",
                        "Address2",
                        "Address3"});
            this._MemoryFrame.Add(this._MemoryAddressList);
            this._MemoryContent.Width = Dim.Fill(0);
            this._MemoryContent.Height = Dim.Fill(0);
            this._MemoryContent.X = Pos.Right(_MemoryAddressList);
            this._MemoryContent.Y = 0;
            this._MemoryContent.ColorScheme = this.Custom;
            this._MemoryContent.Data = "_MemoryContent";
            this._MemoryContent.Text = "";
            this._MemoryContent.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this._MemoryContent.Source = new Terminal.Gui.ListWrapper(new string[] {
                        "Content1",
                        "Content2",
                        "Content3"});
            this._MemoryFrame.Add(this._MemoryContent);
            this._RegistersFrame.Width = Dim.Fill(0);
            this._RegistersFrame.Height = Dim.Fill(0);
            this._RegistersFrame.X = Pos.Right(_MemoryFrame);
            this._RegistersFrame.Y = Pos.Bottom(_PipelineFrame);
            this._RegistersFrame.ColorScheme = this.greenOnBlack;
            this._RegistersFrame.Data = "_RegistersFrame";
            this._RegistersFrame.Text = "";
            this._RegistersFrame.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this._RegistersFrame.Border.Effect3D = false;
            this._RegistersFrame.Border.DrawMarginFrame = true;
            this._RegistersFrame.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this._RegistersFrame.Title = "Registers";
            this.Add(this._RegistersFrame);
            this._RegisterList.Width = Dim.Percent(50f);
            this._RegisterList.Height = Dim.Fill(0);
            this._RegisterList.X = 0;
            this._RegisterList.Y = 0;
            this._RegisterList.ColorScheme = this.Custom;
            this._RegisterList.Data = "_RegisterList";
            this._RegisterList.Text = "";
            this._RegisterList.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this._RegisterList.Source = new Terminal.Gui.ListWrapper(new string[] {
                        "Register1",
                        "Register2",
                        "Register3"});
            this._RegistersFrame.Add(this._RegisterList);
            this._RegisterContent.Width = Dim.Fill(0);
            this._RegisterContent.Height = Dim.Fill(0);
            this._RegisterContent.X = Pos.Right(_RegisterList);
            this._RegisterContent.Y = 0;
            this._RegisterContent.ColorScheme = this.Custom;
            this._RegisterContent.Data = "_RegisterContent";
            this._RegisterContent.Text = "";
            this._RegisterContent.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this._RegisterContent.Source = new Terminal.Gui.ListWrapper(new string[] {
                        "Content1",
                        "Content2",
                        "Content3"});
            this._RegistersFrame.Add(this._RegisterContent);
        }
    }
}
