
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.17.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace THUMDER.CLI {
    using Terminal.Gui;
    
    
    public partial class SettingsDialog {
        
        public SettingsDialog() {
            InitializeComponent();
        }
    }
}
