
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.17.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace THUMDER.CLI {
    using System;
    using Terminal.Gui;
    
    
    public partial class SettingsDialog : Terminal.Gui.Window {
        
        private Terminal.Gui.ColorScheme greenOnBlack;
        
        private Terminal.Gui.ColorScheme Custom;
        
        private Terminal.Gui.ColorScheme greenOnBlack2;
        
        private Terminal.Gui.ColorScheme MenuScheme;
        
        private Terminal.Gui.Wizard wizard1;
        
        private Terminal.Gui.CheckBox _BypassCheck;
        
        private Terminal.Gui.Label label2;
        
        private Terminal.Gui.TextField _memSizeField;
        
        private Terminal.Gui.Label label1;
        
        private Terminal.Gui.TextField _AluNumberField;
        
        private Terminal.Gui.TextField _AluDelayField;
        
        private Terminal.Gui.Label label3;
        
        private void InitializeComponent() {
            this.label3 = new Terminal.Gui.Label();
            this._AluDelayField = new Terminal.Gui.TextField();
            this._AluNumberField = new Terminal.Gui.TextField();
            this.label1 = new Terminal.Gui.Label();
            this._memSizeField = new Terminal.Gui.TextField();
            this.label2 = new Terminal.Gui.Label();
            this._BypassCheck = new Terminal.Gui.CheckBox();
            this.wizard1 = new Terminal.Gui.Wizard();
            this.greenOnBlack = new Terminal.Gui.ColorScheme();
            this.greenOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Green, Terminal.Gui.Color.Black);
            this.greenOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightGreen, Terminal.Gui.Color.Black);
            this.greenOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Green, Terminal.Gui.Color.Magenta);
            this.greenOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightGreen, Terminal.Gui.Color.Magenta);
            this.greenOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Gray, Terminal.Gui.Color.Black);
            this.Custom = new Terminal.Gui.ColorScheme();
            this.Custom.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Black);
            this.Custom.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.Brown);
            this.Custom.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Black);
            this.Custom.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.Brown);
            this.Custom.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Gray, Terminal.Gui.Color.Black);
            this.greenOnBlack2 = new Terminal.Gui.ColorScheme();
            this.greenOnBlack2.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Black);
            this.greenOnBlack2.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightGreen, Terminal.Gui.Color.Black);
            this.greenOnBlack2.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Green, Terminal.Gui.Color.Magenta);
            this.greenOnBlack2.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightGreen, Terminal.Gui.Color.Magenta);
            this.greenOnBlack2.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Gray, Terminal.Gui.Color.Black);
            this.MenuScheme = new Terminal.Gui.ColorScheme();
            this.MenuScheme.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.Gray);
            this.MenuScheme.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Brown, Terminal.Gui.Color.Gray);
            this.MenuScheme.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.DarkGray);
            this.MenuScheme.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Brown, Terminal.Gui.Color.DarkGray);
            this.MenuScheme.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Black);
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Modal = true;
            this.Text = "";
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.Effect3D = false;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "";
            this.wizard1.Width = Dim.Fill(0);
            this.wizard1.Height = Dim.Fill(0);
            this.wizard1.X = Pos.Center();
            this.wizard1.Y = Pos.Center();
            this.wizard1.Modal = true;
            this.wizard1.Data = "wizard1";
            this.wizard1.Text = "";
            this.wizard1.Border.BorderStyle = Terminal.Gui.BorderStyle.Double;
            this.wizard1.Border.Effect3D = true;
            this.wizard1.Border.DrawMarginFrame = true;
            this.wizard1.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.wizard1.Title = "Options";
            this.Add(this.wizard1);
            this._BypassCheck.Width = 6;
            this._BypassCheck.Height = 1;
            this._BypassCheck.X = Pos.Center();
            this._BypassCheck.Y = Pos.Center();
            this._BypassCheck.Data = "_BypassCheck";
            this._BypassCheck.Text = "Bypass";
            this._BypassCheck.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this._BypassCheck.Checked = true;
            this.wizard1.Add(this._BypassCheck);
            this.label2.Width = 4;
            this.label2.Height = 1;
            this.label2.X = Pos.Center();
            this.label2.Y = Pos.Bottom(_BypassCheck) + 1;
            this.label2.Data = "label2";
            this.label2.Text = "Memory Size";
            this.label2.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.wizard1.Add(this.label2);
            this._memSizeField.Width = 11;
            this._memSizeField.Height = 1;
            this._memSizeField.X = Pos.Center();
            this._memSizeField.Y = Pos.Bottom(_BypassCheck) + 2;
            this._memSizeField.Secret = false;
            this._memSizeField.Data = "_memSizeField";
            this._memSizeField.Text = "0x1000000";
            this._memSizeField.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.wizard1.Add(this._memSizeField);
            this.label1.Width = 4;
            this.label1.Height = 1;
            this.label1.X = Pos.Center();
            this.label1.Y = Pos.Bottom(_memSizeField) + 1;
            this.label1.Data = "label1";
            this.label1.Text = "ALU Options";
            this.label1.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.wizard1.Add(this.label1);
            this._AluNumberField.Width = 4;
            this._AluNumberField.Height = 1;
            this._AluNumberField.X = Pos.Center() - 6;
            this._AluNumberField.Y = Pos.Bottom(label1) + 1;
            this._AluNumberField.Secret = false;
            this._AluNumberField.Data = "_AluNumberField";
            this._AluNumberField.Text = "1";
            this._AluNumberField.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.wizard1.Add(this._AluNumberField);
            this._AluDelayField.Width = 4;
            this._AluDelayField.Height = 1;
            this._AluDelayField.X = Pos.Center() + 1;
            this._AluDelayField.Y = Pos.Bottom(label1) + 1;
            this._AluDelayField.Secret = false;
            this._AluDelayField.Data = "_AluDelayField";
            this._AluDelayField.Text = "1";
            this._AluDelayField.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.wizard1.Add(this._AluDelayField);
            this.label3.Width = 4;
            this.label3.Height = 1;
            this.label3.X = Pos.Center();
            this.label3.Y = Pos.Left(_BypassCheck);
            this.label3.Data = "label3";
            this.label3.Text = "Bypass";
            this.label3.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.wizard1.Add(this.label3);
        }
    }
}
